services: 
  bme680:
    container_name: bme680
    image: bme680
    build: 
      context: ./custom/bme680
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      mosquitto:
        condition: service_healthy
      telegraf:
        condition: service_started
      influxdb:
        condition: service_healthy
    environment:
    - TZ=${TZ}
    - IOTSTACK_UID=1000
    - IOTSTACK_GID=1000
    devices:
    - /dev/i2c-1:/dev/i2c-1

  owm:
    container_name: owm
    image: owm
    build: 
      context: ./custom/owm
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      mosquitto:
        condition: service_healthy
      telegraf:
        condition: service_started
      influxdb:
        condition: service_healthy
    environment:
    - TZ=${TZ}
    - IOTSTACK_UID=1000
    - IOTSTACK_GID=1000
    - OWM_API_KEY=${OWM_API_KEY}
    - LATITUDE=${LATITUDE}
    - LONGITUDE=${LONGITUDE}

  sds011:
    container_name: sds011
    image: sds011
    build: 
      context: ./custom/sds011
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      mosquitto:
        condition: service_healthy
      telegraf:
        condition: service_started
      influxdb:
        condition: service_healthy
    environment:
    - TZ=${TZ}
    - IOTSTACK_UID=1000
    - IOTSTACK_GID=1000
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
