version: "3"
services:

  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - airq-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - INFLUXDB_DB
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - airq-network

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/templates/${ENV}:/etc/nginx/templates:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - airq-network
    environment:
      - DOMAIN
    depends_on:
      - influxdb
      - grafana

volumes:
  influxdb:
  grafana:
networks:
  airq-network: